# Generated by Django 6.0.3 on 2026-03-24 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('crear_intercambio', 'Crear intercambio'), ('aceptar_intercambio', 'Aceptar intercambio'), ('rechazar_intercambio', 'Rechazar intercambio'), ('cancelar_intercambio', 'Cancelar intercambio'), ('actualizar_bolsa', 'Actualizar bolsa'), ('sync_calendar', 'Sincronizar calendario')], max_length=50)),
                ('entidad', models.CharField(choices=[('asignacion', 'Asignación'), ('solicitud', 'Solicitud'), ('bolsa', 'Bolsa')], max_length=50)),
                ('id_entidad', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
