# Generated by Django 6.0.3 on 2026-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='entidad',
            field=models.CharField(choices=[('asignacion', 'Asignación'), ('solicitud', 'Solicitud'), ('bolsa', 'Bolsa'), ('semana', 'Semana')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_evento',
            field=models.CharField(choices=[('crear_intercambio', 'Crear intercambio'), ('aceptar_intercambio', 'Aceptar intercambio'), ('rechazar_intercambio', 'Rechazar intercambio'), ('cancelar_intercambio', 'Cancelar intercambio'), ('actualizar_bolsa', 'Actualizar bolsa'), ('publicar_semana', 'Publicar semana'), ('sync_calendar', 'Sincronizar calendario')], max_length=50),
        ),
    ]
