# Generated by Django 6.0.3 on 2026-04-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('intercambio_solicitado', 'Intercambio Solicitado'), ('intercambio_aprobado', 'Intercambio Aprobado'), ('intercambio_rechazado', 'Intercambio Rechazado'), ('vacacion_aprobada', 'Vacacion Aprobada'), ('vacacion_rechazada', 'Vacacion Rechazada'), ('semana_publicada', 'Semana Publicada'), ('incidencia', 'Incidencia')], max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('enlace_entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
