# Generated by Django 6.0.3 on 2026-03-24 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('numero_semana', models.IntegerField()),
                ('fecha_inicio_semana', models.DateField()),
                ('fecha_fin_semana', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
            ],
            options={
                'unique_together': {('anio', 'numero_semana')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20)),
                ('hora_inicio', models.TimeField(default='14:00')),
                ('hora_fin', models.TimeField(default='22:00')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('intercambiado', 'Intercambiado')], default='asignado', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='turnos.calendariosemanal')),
            ],
            options={
                'unique_together': {('semana', 'usuario', 'dia')},
            },
        ),
    ]
