# Generated by Django 6.0.3 on 2026-03-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        ('usuarios', '0003_equipo_usuario_equipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asignaciontarde',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='asignaciontarde',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='asignaciontarde',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('cobertura', 'Cobertura Insuficiente'), ('exceso_horas', 'Exceso de Horas'), ('descanso_insuficiente', 'Descanso Insuficiente (<12h)'), ('conflicto_vacaciones', 'Conflicto con Vacaciones')], max_length=30)),
                ('descripcion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatronRotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('secuencia', models.JSONField(help_text='Secuencia de IDs de PlantillaTurno o null para días libres')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones_rotacion', to='usuarios.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('intercambiado', 'Intercambiado')], default='asignado', max_length=20)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='turnos.calendariosemanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('turno_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='turnos.plantillaturno')),
            ],
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('vacacion', 'Vacación'), ('enfermedad', 'Enfermedad'), ('permiso', 'Permiso Especial')], default='vacacion', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
