# Generated by Django 6.0.3 on 2026-03-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0002_alter_solicitudintercambio_asignacion_destino_and_more'),
        ('turnos', '0002_plantillaturno_alter_asignaciontarde_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionTarde',
        ),
        migrations.AlterUniqueTogether(
            name='asignacionturno',
            unique_together={('semana', 'usuario', 'dia')},
        ),
    ]
