# Generated by Django 6.0.3 on 2026-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_delete_asignaciontarde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
