# Generated by Django 6.0.3 on 2026-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_vacacion_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('limite_horas', 'Límite de Horas'), ('descanso_min', 'Descanso Mínimo'), ('max_turnos', 'Máximo de Turnos')], max_length=20, unique=True)),
                ('valor', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
