# Generated by Django 6.0.3 on 2026-03-25 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionGoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sincronizacion_activa', models.BooleanField(default=False)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
