# Generated by Django 6.0.3 on 2026-04-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0005_add_configuracion_regla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('intercambiado', 'Intercambiado')], default='asignado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_simples', to='turnos.calendariosemanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_simples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['semana__anio', 'semana__numero_semana'],
                'unique_together': {('semana', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudTurnoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_turno_semanal_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_turno_semanal_enviadas', to=settings.AUTH_USER_MODEL)),
                ('turno_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_como_destino', to='turnos_simples.turnosemanal')),
                ('turno_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_como_origen', to='turnos_simples.turnosemanal')),
            ],
        ),
    ]
