# Generated by Django 6.0.3 on 2026-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_simples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudturnosemanal',
            name='modo_compensacion',
            field=models.CharField(choices=[('bolsa', 'Bolsa de días'), ('inmediata', 'Inmediata')], default='bolsa', max_length=20),
        ),
    ]
