# Generated by Django 6.0.3 on 2026-03-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaDiasSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_dias_a_favor_de_a', models.IntegerField(default=0)),
                ('saldo_dias_a_favor_de_b', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BolsaDiasMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('tipo', models.CharField(choices=[('genera_deuda', 'Genera deuda'), ('compensa_deuda', 'Compensa deuda')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to=settings.AUTH_USER_MODEL)),
                ('origen_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
