# Generated by Django 6.0.3 on 2026-03-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsa', '0001_initial'),
        ('intercambios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsadiasmovimiento',
            name='solicitud_intercambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercambios.solicitudintercambio'),
        ),
        migrations.AddField(
            model_name='bolsadiassaldo',
            name='usuario_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_como_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsadiassaldo',
            name='usuario_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_como_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsadiasmovimiento',
            name='saldo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bolsa.bolsadiassaldo'),
        ),
        migrations.AlterUniqueTogether(
            name='bolsadiassaldo',
            unique_together={('usuario_a', 'usuario_b')},
        ),
    ]
