# Generated by Django 6.0.3 on 2026-04-08 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0003_solicitudcompensacionbolsa'),
        ('turnos_simples', '0002_solicitudturnosemanal_modo_compensacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsadiasmovimiento',
            name='solicitud_semanal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_simples.solicitudturnosemanal'),
        ),
    ]
