# Generated by Django 6.0.3 on 2026-03-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0001_initial'),
        ('turnos', '0002_plantillaturno_alter_asignaciontarde_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudintercambio',
            name='asignacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_destino', to='turnos.asignacionturno'),
        ),
        migrations.AlterField(
            model_name='solicitudintercambio',
            name='asignacion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_origen', to='turnos.asignacionturno'),
        ),
        migrations.AlterField(
            model_name='solicitudintercambio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
